### ISSUE TITLE
ERROR: QA Issue: alljoyn-services: Files/directories were installed but not shipped

### ISSUE THREAD

**Issue by murphy666** [hjourdain/meta-alljoyn#1]
First, thank you for providing this layer!

So, When building alljoyn-service I receive QA Issue, I'm building  the git version:

12:56:03 ERROR: QA Issue: alljoyn-services: Files/directories were installed but not shipped
12:56:03   /opt/alljoyn/bin/.debug
12:56:03   /opt/alljoyn/bin/.debug/AboutService
12:56:03   /opt/alljoyn/bin/.debug/ConfigService
12:56:03   /opt/alljoyn/bin/.debug/ConfigClient
12:56:03   /opt/alljoyn/bin/.debug/ControlPanelProducer
12:56:03   /opt/alljoyn/bin/.debug/ProducerBasic
12:56:03   /opt/alljoyn/bin/.debug/ControlPanelSample
12:56:03   /opt/alljoyn/bin/.debug/ControlPanelController
12:56:03   /opt/alljoyn/bin/.debug/TestService
12:56:03   /opt/alljoyn/bin/.debug/AboutClient
12:56:03   /opt/alljoyn/bin/.debug/ProducerService
12:56:03   /opt/alljoyn/bin/.debug/OnboardingClient
12:56:03   /opt/alljoyn/bin/.debug/AboutService_legacy
12:56:03   /opt/alljoyn/bin/.debug/onboarding-daemon
12:56:03   /opt/alljoyn/bin/.debug/AboutClient_legacy
12:56:03   /opt/alljoyn/bin/.debug/ConsumerService
12:56:03   /opt/alljoyn/bin/.debug/ACServerSample [installed-vs-shipped]

**Comment by hjourdain** [comment]
Hi,

May I ask what version of yocto/poky you’re using?

Herve

**Comment by murphy666** [comment]
Sorry, I'm using Fido version.

**Comment by hjourdain** [comment]
Hi,

That’s strange, I can’t reproduce it… I’ve tried to build it in several Yocto environments, but it seems to build fine for me.

Did you try with a different version of Yocto? And do you still see the same?

Herve

**Comment by hjourdain** [comment]
Hi,

One question, do you have dbg-pkgs added to your EXTRA_IMAGE_FEATURES?

I’m not sure if that’s the reason of your issue, but I’ve noticed it’s always set on my test environments.

Herve

From: Herve Jourdain [mailto:herve.jourdain@neuf.fr] 
Sent: mardi 31 mai 2016 09:37
To: 'hjourdain/meta-alljoyn' reply@reply.github.com; 'hjourdain/meta-alljoyn' meta-alljoyn@noreply.github.com
Cc: 'Comment' comment@noreply.github.com
Subject: RE: [hjourdain/meta-alljoyn] ERROR: QA Issue: alljoyn-services: Files/directories were installed but not shipped (#1)

Hi,

That’s strange, I can’t reproduce it… I’ve tried to build it in several Yocto environments, but it seems to build fine for me.

Did you try with a different version of Yocto? And do you still see the same?

Herve

**Comment by murphy666** [comment]
For some reason I cannot reproduce anymore, anyway I can clearly see that the dbg package is properly defined there is no reason for this to fail.

Thanks you for you support!
